# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.cache/wt} [current_project]
set_property parent.project_path {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/res/weights.coe}}
add_files {{C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/res/00.coe}}
read_verilog -library xil_defaultlib {
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/new/BRAM_RJ_page1.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/new/BRAM_RJ_page2.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/new/BRAM_end.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/new/BRAM_menu1.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/ee2026/proj base - Copy/MODS.xpr/MODS/MODS.srcs/sources_1/new/BRAM_poop.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/ee2026/proj base - Copy/MODS.xpr/MODS/MODS.srcs/sources_1/new/BRAM_pullup_down.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/ee2026/proj base - Copy/MODS.xpr/MODS/MODS.srcs/sources_1/new/BRAM_pullup_up.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/ee2026/proj base - Copy/MODS.xpr/MODS/MODS.srcs/sources_1/new/BRAM_pushup_down.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/new/BRAM_pushup_up.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/ee2026/proj base - Copy/MODS.xpr/MODS/MODS.srcs/sources_1/new/BRAM_run1.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/ee2026/proj base - Copy/MODS.xpr/MODS/MODS.srcs/sources_1/new/BRAM_run3.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/ee2026/proj base - Copy/MODS.xpr/MODS/MODS.srcs/sources_1/new/BRAM_run4.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/ee2026/proj base - Copy/MODS.xpr/MODS/MODS.srcs/sources_1/new/BRAM_run6.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/ee2026/proj base - Copy/MODS.xpr/MODS/MODS.srcs/sources_1/new/BRAM_situp_down.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/ee2026/proj base - Copy/MODS.xpr/MODS/MODS.srcs/sources_1/new/BRAM_situp_up.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/new/Keith_module.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/new/MUX_control.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/EE2026labs/calorie_tracker/calorie_tracker.srcs/sources_1/new/Main_Control.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/Desktop/Oled_Display.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/new/Project_MUX.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/new/RJ_Main.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/new/RJ_OLED_Control.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/new/RJ_menu.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/EE2026labs/calorie_tracker/calorie_tracker.srcs/sources_1/new/calorie_led.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/EE2026labs/calorie_tracker/calorie_tracker.srcs/sources_1/new/calorie_menu.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/EE2026labs/calorie_tracker/calorie_tracker.srcs/sources_1/new/dff.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/new/flexible_clock.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/EE2026labs/calorie_tracker/calorie_tracker.srcs/sources_1/new/numpad_digits.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/EE2026labs/calorie_tracker/calorie_tracker.srcs/sources_1/new/oled_data_mux.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/EE2026labs/calorie_tracker/calorie_tracker.srcs/sources_1/new/snack_menu.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/ee2026/proj base - Copy/MODS.xpr/MODS/MODS.srcs/sources_1/new/top.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/imports/ee2026/proj base - Copy/MODS.xpr/MODS/MODS.srcs/sources_1/new/workout.v}
  {C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/sources_1/new/Top_Student.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/constrs_1/new/master_constraint.xdc}}
set_property used_in_implementation false [get_files {{C:/school/uni stuff/y2s2/ee2026/FINAL_v7.1.xpr/MODS/MODS.srcs/constrs_1/new/master_constraint.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_Student -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Student.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Student_utilization_synth.rpt -pb Top_Student_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
